### PR TITLE
Random word

### PR DESCRIPTION
**Pull request by BertrandBurel**
- Add 5 attemps limit;
- change rules;
- add win / loose message with redirection

### CODE REVIEW

**Review by MaximeSaliou72 — APPROVED** [review]
Correct

**Review by GuillaumeCabaret — APPROVED** [review]
ok for me !

**Review by BenjaminPerrin — APPROVED** [review]
gg

**Review by Ylrah — APPROVED** [review]
nice !

**Review by Vmalleron — COMMENTED** [review]
ok

**Review by Vmalleron — APPROVED** [review]
ok

**Pull request merged**
