### PR TITLE
fixe deploy.sh

### PR DESCRIPTION
**Pull request by MaximeSaliou72**
Problem with deploy.sh fixed

### CODE REVIEW

**Review by BertrandBurel — APPROVED** [review]
OK.

**Review by jordanLeveque — APPROVED** [review]
nice

**Review by paulMorea — APPROVED** [review]
good

**Review by CastellierGwenole — APPROVED** [review]

**Review by Vmalleron — APPROVED** [review]
it's ok

**Review by yohannmartinez — APPROVED** [review]

**Pull request merged**
